name: Conditionals Demo 2

on: 
  workflow_dispatch:

jobs:
  conditional_job:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Step that runs only on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Running only on main branch"
          echo "Event = ${{ github.event_name }}"
      
      - name: Step that fails intentionally
        id: fail_step
        run: exit 1
        continue-on-error: true
      
      - name: Run only if previous step failed
        if: failure()
        run: echo "Previous step failed!"