name: Secret Environment Example

on: 
  workflow_dispatch:

jobs:
  use-secret-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pas Secrets as environment Variables
        env:
          Docker_username: ${{ secrets.DOCKER_USERNAME }}
          Docker_password: ${{ secrets.DOCKER_TOkEN }}
        run: |
          echo "Logging into Docker"
          echo "$Docker_password" | docker login -u "$Docker_username" --password-stdin