name: Docker Build

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v4

      - name: Build the docker image
        run: docker build -t my-node-app:latest .