name: Hello Wrokflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
        
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
        
      - name: Print current date and time
        run: date

      - name: Print Branch Name
        run: echo "Branch name is ${{ github.ref_name }}"

      - name: List repository files
        run: ls -la

      - name: Print runner OS
        run: echo "Runner OS is $RUNNER_OS"
