name: PR Check

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Workflow triggered"
