name: Secret Test

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret exists
        run: |
          if [ -n "${{secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "the secret is set : true"
          else
            echo "the secret is set : false"
          fi
        
      - name: Print the secret value
        run: |
          echo "the secret value is : ${{secrets.MY_SECRET_MESSAGE}}"