name: Check tools

on: 
  workflow_dispatch:

jobs:
  check_tools:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PreInstalled Tools
        run: |
          docker --version
          python --version
          node --version
          git --version